### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by xmgeorge** [Homebrew/homebrew-apache#67]
i tried to install this on mac OS X version 10.9.5

brew install httpd24 php55 --with-mysql --with-homebrew-apache --homebrew-apxs -v

exit with this error 

local/Cellar/apr-util/1.5.4/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/Cellar/apr/1.5.1/libexec/lib/libapr-1.la -lpthread
Undefined symbols for architecture x86_64:
  "_TLSv1_1_client_method", referenced from:
      _main in ab.o
  "_TLSv1_2_client_method", referenced from:
      _main in ab.o
ld: symbol(s) not found for architecture x86_64

**Comment by alanthing** [comment]
Please install httpd24 and php55 separately. Also, use `brew info php55` and make sure you're using the correct build options; I don't think `--with-homebrew-apache` is a valid choice.

**Comment by jrsand** [comment]
I got this exact same error. 10.9.5. The way I got past it was to add --with-homebrew-openssl when brew install httpd24.  You can see the errors are TLS... which seems like some symbols are missing from the mac install of whatever ssl stuff it uses.

**Comment by VGerris** [comment]
I encounter this on 10.12.5 too.
I tracked it to the configure script doing something unexpected with SSL detection on some setups.
Somewhere around line 25780 there is ```
 if ac_fn_c_try_compile "$LINENO"; then :
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: OK" >&5
$as_echo "OK" >&6; }
       ac_cv_openssl=yes
else
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: FAILED" >&5
$as_echo "FAILED" >&6; }
fi
```
I am unsure how the openssl is determined exactly, but on my system where I have OpenSSL libraries installed by homebrew it still detects an older version and compiles, while at the machine of a colleague it does detect it and fails after.

An ugly workaround to get it to compile is to set this:
`ac_cv_openssl=no` 
instead of yes.

Make sure to do a make clean, there may be already compiled modules that mess up the compile.
So:
```
make clean
./configure --with-all-your-nice-options
make -j install
```

If anyone knows the source of the issue, please let us know.
