### ISSUE TITLE
Request: Build mod_wsgi against homebrew python3

### ISSUE THREAD

**Issue by drmaj** [Homebrew/homebrew-apache#77]
Would be great if we could install mod_wsgi using the python3 homebrew installation.

**Comment by M0rtenB** [comment]
Seconded.

**Comment by benjaminblack** [comment]
Thirded.

This can easily be done by building directly from the source, passing "--with-python=python3" to configure:

    $ ./configure --with-python=python3
    $ make; sudo make install

And confirming the compile module is linked with Python 3:

    $ otool -l /usr/libexec/apache2/mod_wsgi.so | grep Python
             name /usr/local/Frameworks/Python.framework/Versions/3.5/Python (offset 24)

Should be relatively easy to add a build option to the Formula?

**Comment by benjaminblack** [comment]
Workaround -- Edit the formula:

    $ brew edit mod_wsgi

Step 1: Change the homebrew-python dependency to python3 instead of python -- Change line 31 from:
    depends_on "python" if build.with? "homebrew-python"

To:
    depends on "python3" if build.with? "homebrew-python"


Step 2: Change the build option on line 70 from:
        args << "--with-python=#{HOMEBREW_PREFIX}/bin/python" if build.with? "homebrew-python"

To:
        args << "--with-python=#{HOMEBREW_PREFIX}/bin/python3" if build.with? "homebrew-python"

This will link the shared object against Python 3.

Then
    $ brew install mod_wsgi

And it should build it and link against Python 3.

Confirm the resulting binary is linked with:
    otool -L /usr/local/Cellar/mod_wsgi/4.4.11/libexec/mod_wsgi.so

And you should see:
    /usr/local/Cellar/mod_wsgi/4.4.11/libexec/mod_wsgi.so:
            /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python (compatibility version 3.5.0, current version 3.5.0)

**Comment by yosuah** [comment]
@benjaminblack thank you for the detailed instructions. I've ran into this same issue - would it be possible to add a --with-homebrew-python3 option as well to avoid everyone having to do this?

**Comment by benjaminblack** [comment]
@yosuah Sure, I didn't bother originally because it's a fairly trivial change to the "formula", but I did it now and submitted a pull request. It's up to the maintainers now.

**Comment by yosuah** [comment]
@benjaminblack thanks a lot, much appreciated.

**Comment by hvt23715** [comment]
Warning!  dlname not found in /usr/libexec/apache2/mod_wsgi.la.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/libexec/apache2/mod_wsgi.so
chmod: /usr/libexec/apache2/mod_wsgi.so: No such file or directory
apxs:Error: Command failed with rc=65536
.
make: *** [install] Error 1


why??

**Comment by zagros** [comment]
@hvt23715 did you find the resolution for that error? I'm getting the exact same issue

**Comment by anton-petrov** [comment]
I have the same error:
Warning!  dlname not found in /usr/local/Cellar/mod_wsgi/4.5.7/libexec/mod_wsgi.la.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/mod_wsgi/4.5.7/libexec/mod_wsgi.so
chmod: /usr/local/Cellar/mod_wsgi/4.5.7/libexec/mod_wsgi.so: No such file or directory
apxs:Error: Command failed with rc=65536

**Comment by portergoh** [comment]
Hi

Anyone managed to solve this issue

Having same issue too
Warning!  dlname not found in /usr/local/Cellar/mod_wsgi/4.5.7/libexec/mod_wsgi.la.

**Comment by ilovezfs** [comment]
@portergoh does https://github.com/Homebrew/homebrew-apache/pull/147 work for you?

**Comment by portergoh** [comment]
Hi ilovezfs,

Thanks it works now :)

**Comment by mistergoodson** [comment]
I'm getting the same error as @portergoh:
`chmod: /usr/local/Cellar/mod_wsgi/4.5.7/libexec/mod_wsgi.so: No such file or directory`

I only have the default Apple Apache install. Will try with Homebrew's httpd next.

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated. This can be done with `APXS=/usr/local/opt/httpd/bin/apxs  /usr/local/opt/python3/bin/pip3 install mod_wsgi` once you have done `brew install httpd python3`.
