### ISSUE TITLE
Missing symlink after installing ab

### ISSUE THREAD

**Issue by tuxone** [Homebrew/homebrew-apache#98]
On OSX 10.11.1

``` shell
$ brew install homebrew/apache/ab
...
$ which ab
/usr/sbin/ab
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ ls /usr/local/bin/ab
ls: /usr/local/bin/ab: No such file or directory
$ cd /usr/local/bin/
$ ln -s ../Cellar/ab/2.4.16/bin/ab ./
$ which ab
/usr/local/bin/ab
```

**Comment by javian** [comment]
This is intended behaviour. Since ab is shipped with OSX the Formula is installed with `keg_only :provided_by_osx` meaning that it will not install symlinks into the path.

**Comment by tuxone** [comment]
Hi @javian, I know OSX comes with ab but if I'm installing it trough brew I expect the Formula replaces the preinstalled version. If I'm correct this is the current behavior of git and php Formulas for example

**Comment by javian** [comment]
There's an entry for this in the faq https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md#what-does-keg-only-mean

some tools are not linked because they can cause issues with the system and interfere with other software but yes you are right - there are some tools that ship with OSX that is linked by default.

**Comment by MikeMcQuaid** [comment]
Run `brew install httpd` to get this formula (and symlink) now.
